version: "0.2"
language: en
words:
  - apos
  - asar
  - autorun
  - bivariance
  - bivariant
  - callsite
  - unapply
  - chrono
  - chromedriver
  - collab
  - eemeli
  - haspopup
  - iconed
  - inlang
  - Initializable
  - invertibility
  - Keymap
  - labelledby
  - lezer
  - liamcain
  - linkpath
  - linktext
  - longtext
  - macrotask
  - multitext
  - nanoevents
  - nanoids
  - obsidianmd
  - offref
  - paraglide
  - parameterless
  - passthroughs
  - popout
  - prefs
  - previewable
  - rangeset
  - reanchor
  - recentered
  - recenters
  - recomputable
  - renderable
  - rescan
  - реліз
  - спринт
  - spinbutton
  - Standups
  - subpages
  - templater
  - tfile
  - unapplies
  - unitless
  - unmappable
  - unpadded
  - unrecognised
  - unrenderable
  - unshifted
  - vnode
  - vueuse
  - wdio
  - wikilinks
  - worktree
ignorePaths:
  - node_modules
  - build
  - coverage
  - test-vault
  - "*.snap"
  - package-lock.json
