version: "0.2"
language: en
words:
  - bivariance
  - bivariant
  - callsite
  - unapply
  - chrono
  - collab
  - iconed
  - inlang
  - Keymap
  - lezer
  - offref
  - paraglide
  - passthroughs
  - popout
  - rangeset
  - spinbutton
  - subpages
  - templater
ignorePaths:
  - node_modules
  - build
  - coverage
  - test-vault
  - src/_old-code
  - "*.snap"
  - package-lock.json
