// Obsidian theme CSS-variable names offered by the theme color picker. The variable name
// is the identifier stored in settings; the dropdown shows it verbatim with a live swatch.
export const THEME_COLOR_NAMES: readonly string[] = [
  "background-primary",
  "background-primary-alt",
  "background-secondary",
  "background-secondary-alt",
  "background-modifier-hover",
  "background-modifier-active-hover",
  "background-modifier-border",
  "background-modifier-border-hover",
  "background-modifier-border-focus",
  "background-modifier-error-rgb",
  "background-modifier-error",
  "background-modifier-error-hover",
  "background-modifier-success-rgb",
  "background-modifier-success",
  "background-modifier-message",
  "interactive-normal",
  "interactive-hover",
  "interactive-accent",
  "interactive-accent-hover",
  "text-normal",
  "text-muted",
  "text-faint",
  "text-on-accent",
  "text-on-accent-inverted",
  "text-success",
  "text-warning",
  "text-error",
  "text-accent",
  "text-accent-hover",
  "text-selection",
  "text-highlight-bg",
  "caret-color",
];
