import { CalendarConfig } from "../contracts/config.types";

export const DEFAULT_CONFIG_CALENDAR: CalendarConfig = {
  id: "my-journal",
  type: "calendar",
  name: "My Journal",
  isDefault: true,
  rootFolder: "",
  openOnStartup: false,
  startupSection: "daily",

  daily: {
    enabled: true,
    openMode: "active",
    titleTemplate: "{{date}}",
    dateFormat: "YYYY-MM-DD",
    folder: "",
    template: "",
    ribbon: {
      show: true,
      icon: "",
      tooltip: "",
    },
    createOnStartup: false,
  },
  weekly: {
    enabled: false,
    openMode: "active",
    firstDayOfWeek: -1,
    firstWeekOfYear: 1,
    titleTemplate: "{{date}}",
    dateFormat: "YYYY-[W]ww",
    folder: "",
    template: "",
    ribbon: {
      show: false,
      icon: "",
      tooltip: "",
    },
    createOnStartup: false,
  },
  monthly: {
    enabled: false,
    openMode: "active",
    titleTemplate: "{{date}}",
    dateFormat: "YYYY-MM",
    folder: "",
    template: "",
    ribbon: {
      show: false,
      icon: "",
      tooltip: "",
    },
    createOnStartup: false,
  },
  quarterly: {
    enabled: false,
    openMode: "active",
    titleTemplate: "{{date}}",
    dateFormat: "YYYY-[Q]Q",
    folder: "",
    template: "",
    ribbon: {
      show: false,
      icon: "",
      tooltip: "",
    },
    createOnStartup: false,
  },
  yearly: {
    enabled: false,
    openMode: "active",
    titleTemplate: "{{date}}",
    dateFormat: "YYYY",
    folder: "",
    template: "",
    ribbon: {
      show: false,
      icon: "",
      tooltip: "",
    },
    createOnStartup: false,
  },
};
