import { describe, expect, it } from "vitest";
import { looseListLines, releaseNotes, releaseSections } from "./changelog.mjs";

const CHANGELOG = `# Changelog

All notable changes to this project will be documented in this file.

## [3.5.1] - 2026-09-20

### Changed

- No change to the plugin itself.

## [3.5.0] - 2026-09-20

### Features

- Settings sections now link to the manual.
- Bulk add can now read a note's date from where the note sits.

### Bug Fixes

- Opening a journal note no longer steals focus.

## [3.4.0] - 2026-09-12

### Features

- Views can carry a toolbar.

<!-- generated by git-cliff -->
`;

describe("releaseSections", () => {
  it("names every release, newest first", () => {
    expect(releaseSections(CHANGELOG).map((section) => section.version)).toEqual(["3.5.1", "3.5.0", "3.4.0"]);
  });

  it("reads an Unreleased section like any other", () => {
    const text = "# Changelog\n\n## [Unreleased]\n\n### Features\n\n- Something.\n";
    expect(releaseSections(text).map((section) => section.version)).toEqual(["Unreleased"]);
  });

  it("records the heading's line number", () => {
    expect(releaseSections(CHANGELOG).map((section) => section.lineno)).toEqual([5, 11, 22]);
  });

  it("finds nothing in a changelog with no releases", () => {
    expect(releaseSections("# Changelog\n\nNothing yet.\n")).toEqual([]);
  });
});

describe("releaseNotes", () => {
  it("returns the section body without its heading", () => {
    expect(releaseNotes(CHANGELOG, "3.5.1")).toBe("### Changed\n\n- No change to the plugin itself.");
  });

  it("stops at the next release heading", () => {
    expect(releaseNotes(CHANGELOG, "3.5.0")).toBe(
      [
        "### Features",
        "",
        "- Settings sections now link to the manual.",
        "- Bulk add can now read a note's date from where the note sits.",
        "",
        "### Bug Fixes",
        "",
        "- Opening a journal note no longer steals focus.",
      ].join("\n"),
    );
  });

  it("drops the generator comment trailing the last section", () => {
    expect(releaseNotes(CHANGELOG, "3.4.0")).toBe("### Features\n\n- Views can carry a toolbar.");
  });

  it("returns null for a version the file does not carry", () => {
    expect(releaseNotes(CHANGELOG, "9.9.9")).toBeNull();
  });
});

describe("looseListLines", () => {
  it("passes a changelog whose lists are tight", () => {
    expect(looseListLines(CHANGELOG)).toEqual([]);
  });

  it("reports a blank line between two bullets", () => {
    const text = "# Changelog\n\n## [1.0.0] - 2026-01-01\n\n### Features\n\n- One.\n\n- Two.\n";
    expect(looseListLines(text)).toEqual([{ lineno: 8, version: "1.0.0" }]);
  });

  it("reports a blank line between a wrapped bullet and the next", () => {
    const text = "# Changelog\n\n## [1.0.0] - 2026-01-01\n\n### Features\n\n- One,\n  wrapped.\n\n- Two.\n";
    expect(looseListLines(text)).toEqual([{ lineno: 9, version: "1.0.0" }]);
  });

  it("allows the blank line before a subsection heading", () => {
    const text = "# Changelog\n\n## [1.0.0] - 2026-01-01\n\n### Features\n\n- One.\n\n### Bug Fixes\n\n- Two.\n";
    expect(looseListLines(text)).toEqual([]);
  });

  it("allows the blank line before the next release heading", () => {
    const text = "# Changelog\n\n## [1.1.0]\n\n### Features\n\n- Two.\n\n## [1.0.0]\n\n### Features\n\n- One.\n";
    expect(looseListLines(text)).toEqual([]);
  });

  it("allows a blank line inside a fenced block a bullet carries", () => {
    const text = [
      "# Changelog",
      "",
      "## [1.0.0]",
      "",
      "### Features",
      "",
      "- One:",
      "",
      "  ```",
      "  a",
      "",
      "  b",
      "  ```",
      "- Two.",
      "",
    ].join("\n");
    expect(looseListLines(text)).toEqual([]);
  });

  it("ignores a loose list outside any release section", () => {
    const text = "# Changelog\n\n- One.\n\n- Two.\n\n## [1.0.0]\n\n### Features\n\n- Three.\n";
    expect(looseListLines(text)).toEqual([]);
  });

  it("names the release each finding sits in", () => {
    const text =
      "# Changelog\n\n## [2.0.0]\n\n### Features\n\n- A.\n\n- B.\n\n## [1.0.0]\n\n### Features\n\n- C.\n\n- D.\n";
    expect(looseListLines(text)).toEqual([
      { lineno: 8, version: "2.0.0" },
      { lineno: 16, version: "1.0.0" },
    ]);
  });
});
