name: Checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24.x'
      - run: npm ci
      - run: npm run compile:i18n
      - run: npm run check:types
      - run: npm test
      - run: npm run check:lint
