permissions: write-all
name: Release Obsidian plugin

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: get version
        run: echo "PACKAGE_VERSION=$(node -p "require('./manifest-beta.json').version")" >> $GITHUB_ENV
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version="${process.env.PACKAGE_VERSION}"

          gh release create "$version" \
            --title="$version" \
            --draft \
            build/main.js manifest.json build/styles.css
