permissions: write-all
name: Release Obsidian plugin (beta)

on: workflow_dispatch

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      PACKAGE_VERSION: ${{ steps.version.outputs.PACKAGE_VERSION }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - id: version
        name: Get version
        run: echo "PACKAGE_VERSION=$(node -p "require('./manifest-beta.json').version")" >> "$GITHUB_OUTPUT"
  build:
    runs-on: ubuntu-latest
    needs: [get-version]
    env:
      PACKAGE_VERSION: ${{ needs.get-version.outputs.PACKAGE_VERSION }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci

      - name: Run checks
        run: |
          npm run ts-check
          npm test

      - name: Build plugin
        run: |
          npm run build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=${{ env.PACKAGE_VERSION }}

          gh release create "$version" \
            --title="$version" \
            --draft \
            build/main.js manifest.json build/styles.css
